####################################################################################
# Docker-compose file for spinning up a uber-cron container
# USAGE: docker-compose up -d
#
####################################################################################

version: '3.2'

services:
  uber-cron:
    container_name: uber-cron
    hostname: uber-cron
    build:
      context: .
      dockerfile: Dockerfile
    image: uber-cron:latest
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - "127.0.0.1:9229:9229" # Node debugging port
